const { default: mongoose } = require("mongoose")
const mongooose=require("mongoose")

const orderScheme=new mongooose.Schema({
    shippingInfo:{
        address:{
            type:String,
            required:true},
        city:{
            type:String,
            required:true 
        },
        country:{
            type:String,
            required:true
        },
        pinCode:{
            type:Number,
            require:true
        },
    },
    orderItems:[{
        name:{
            type:String,
            required:true
        },
        price:{
            type:Number,
            require:true
        },
        quantity:{
            type:Number,
            required:true
        },
        image:{
           type:String,
           required:true
        },
        product:{
            type:mongoose.Schema.ObjectId,
            ref:"Product",
            required:true
        },
    }
],
    user:{
        type:mongoose.Schema.ObjectId,
        ref:"User",
        required:true
    },
    paymentInfo:{
        id:{
            type:String,
            required:true,
        },
        status:{
            type:String,
            required:true
        }},
        
        paidAt:{
          type:Date,
          required:true,
          default:0
        },

        itemsPrice:{
            type:Number,
            required:true,  
            default:0
        },
        taxPrice:{
            type:Number,
            default:0,
            required:true
        },
        shippingPrice:{
            type:Number,
            required:true,
            default:0
        },
        totalPrice:{
            type:Number,
            required:true,
            defaut:0
        },
        orderStatus:{
            type:String,
            required:true,
            default:"Processing"
        },
        deliveredAt:Date,
        createdAt:{
            type:Date,
            default:Date.now,
        }
})

module.exports=mongooose.model("Order",orderScheme)